sentences = [
    "The sky is blue.",
    "I love coffee.",
    "Today is a great day.",
    "She walks to work.",
    "Music makes me happy.",
    "The cat is sleeping.",
    "My favorite color is red.",
    "I enjoy reading books.",
    "Time flies fast.",
    "It is raining outside.",
    "Birds are singing.",
    "The sun is shining bright.",
    "I will call you later.",
    "Let's go for a walk.",
    "Dinner smells delicious.",
    "I like to travel.",
    "The train is on time.",
    "He plays the guitar.",
    "We are watching a movie.",
    "Life is full of surprises."
]
